--vision 테이블에 min, max 추가
ALTER TABLE t_vision_raw
	add column A1U_min float8,
	add column A2U_min float8,
	add column A3U_min float8,
	add column A4U_min float8,
	add column TS_U_min float8,
	add column A5U_min float8,
	add column A6U_min float8,
	add column A1L_min float8,
	add column A2L_min float8,
	add column A3L_min float8,
	add column A4L_min float8,
	add column TS_A_min float8,
	add column TW_I_min float8,
	add column TW_min float8,
	add column A5L_min float8,
	add column A6L_min float8,
	add column TH_A_min float8,
	add column SM1_min float8,
	add column SM2_min float8,
	add column SM3_min float8,
	add column SM4_min float8,
	add column t2s2_min float8,
	add column sf1u_min float8,
	add column sf2u_min float8,
	add column sf1l_min float8,
	add column sf2l_min float8,
	add column inside_b_min float8,
	add column inside_t_min float8,
	add column g2_min float8,
	add column A1U_max float8,
	add column A2U_max float8,
	add column A3U_max float8,
	add column A4U_max float8,
	add column TS_U_max float8,
	add column A5U_max float8,
	add column A6U_max float8,
	add column A1L_max float8,
	add column A2L_max float8,
	add column A3L_max float8,
	add column A4L_max float8,
	add column TS_A_max float8,
	add column TW_I_max float8,
	add column TW_max float8,
	add column A5L_max float8,
	add column A6L_max float8,
	add column TH_A_max float8,
	add column SM1_max float8,
	add column SM2_max float8,
	add column SM3_max float8,
	add column SM4_max float8,
	add column t2s2_max float8,
	add column sf1u_max float8,
	add column sf2u_max float8,
	add column sf1l_max float8,
	add column sf2l_max float8,
	add column inside_b_max float8,
	add column inside_t_max float8,
	add column g2_max float8;

--실린더 권한 부여
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 967, 'N', 'N', 'N', 'N');
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 999, 'N', 'N', 'N', 'N');
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 1000, 'N', 'N', 'N', 'N');
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 1001, 'N', 'N', 'N', 'N');
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 1002, 'N', 'N', 'N', 'N');
INSERT INTO t_auth_gr_menu_mapp (auth_gr_no, menu_no, home_yn, c, u, d) VALUES(1, 1003, 'N', 'N', 'N', 'N');
